name: "dhis2: artifact-preview"
on:
  push:
  pull_request:
jobs:
  download-webapp-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: upload.yml
          workflow_conclusion: success
          repo: "dhis2/capture-app"
          name: build
          path: build

      - name: Deploy artifact
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './build/app'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-commit-comment: false
          enable-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
